version : '3.9'

services:
  fastapi:
    build:
      context: ./code/
      dockerfile: Dockerfile
    container_name: fastapi
    env_file:
      - .env
    volumes:
      - ./code/:/app/
      - ./code/static/:/app/static/
    ports:
      - "8000:8000"
    networks:
        - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - fastapi
      #- frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network

  frontend:
    container_name: vue
    build:
      context: ./front
      dockerfile: Dockerfile
    #volumes:
      #- ./front/:/app/
    ports:
      - 4173:4173
    networks:
      - app-network
  
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email it.dpm@emk.ru --agree-tos --no-eff-email -d meeting.mosckba.ru
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
